# This section is just used to bootstrap the project. It can be safely removed.
[template]
[template.environment]
  PAYLOAD_SECRET = "Payload secret, used to encrypt JWT tokens"
  MONGODB_URI = "Define your database connection string. If using MongoDB, define the connection string here:"
  POSTGRES_URI = "Alternatively, define the PostgreSQL connection string here:"

[build]
  command = "pnpm build"
  publish = ".next"

[build.environment]
  NPM_FLAGS = "--unsafe-perm"
  NPM_CONFIG_PLATFORM = "linux"
  NPM_CONFIG_ARCH = "x64"
